GET https://localhost:8000/api/products
Content-Type: application/json
//Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1OTc0ODYzMTAsImV4cCI6MTU5NzQ4OTkxMCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6IlNpcml1cyJ9.rCKHS6xrK3Z7kdDhAQy7i6ydfpD8qc7LercVBiVsGKEaFay02jFYYRFcTMtepaEoU2iQyr3dbDR32prlJ5GpViAB5od0WaYre8GJcpdF70tWhUN3l6Zgx7TNON3yf1enRxeoxBbEKKCKUlVqjOwZApkA5moRVvjWj9HChiEDoOK7_PSrlD9ok2sU6mWgpZI5yF08R_WbT7F7kq7iM_VvxdWQn8N7uXWmyhY5nxlYUa0YP4oh_7nohM9bZ9xoVqtqzbICEHTjLveBx4ywMx0pdZxIsKJr1vbv0JwyCnKjaMI4OUGpOYIISTZ-BIY5kqOft4pEXP3uKq9MahG3QT7IXLnUm3VVQRmi68nKOJ_8K2Msil0BLBcOk74X03wrLkm4ulZVHWfj-8NA6KQA4jjYrK1sUXZU9sGFkUlv7NhbLiBNWGXCBWy5dUrTpj-yIRC9Jio7L7j5HVBKh5Ot22AbYUHUa9yrkq3WE_2XOKmjwbfbKuUkIE7RhZ7yZbXzsj1SCczBLWi8RGJIjt3rukGXgkIMUXf4Nhf26XQzCTuxCb97feOr7_wbT-IvCogDiwiHNU6rK1-7ZA-kIM1xMcuMquU4G_6r5HvSXyOy07qZeSPfMGfqDjPLeLP3DmgtS9gvxly9LaUWjXb5u--fiOqL6qokcuKaOPstiDTXp19gXTQ

{
  "title": "Mon titre",
  "content": "Mon contenu"
}